from regelum.core import (
    CompileError,
    CompileIssue,
    CompileReport,
    Connection,
    Elif,
    Else,
    ElseIf,
    Goto,
    If,
    Input,
    InputPort,
    Node,
    NodeInputs,
    NodeOutputs,
    Output,
    OutputPort,
    Phase,
    PhasedReactiveSystem,
    StepRecord,
    Transition,
    V,
    always,
    compile_nodes,
    connect,
    port,
    terminate,
)

try:
    from ._version import __version__
except ImportError:
    __version__ = "0.0.0"

__all__ = [
    "CompileError",
    "CompileIssue",
    "CompileReport",
    "Connection",
    "Elif",
    "Else",
    "ElseIf",
    "Goto",
    "If",
    "Input",
    "InputPort",
    "Node",
    "NodeInputs",
    "NodeOutputs",
    "Output",
    "OutputPort",
    "Phase",
    "PhasedReactiveSystem",
    "StepRecord",
    "Transition",
    "V",
    "always",
    "compile_nodes",
    "connect",
    "port",
    "terminate",
    "__version__",
]
