site_name: Regelum
site_description: Modular framework for pipeline construction
site_author: AIDA Group
docs_dir: ./docs/src
# Repository
repo_name: aidagroup/regelum
repo_url: https://github.com/aidagroup/regelum

# Configuration
theme:
  name: material
  custom_dir: ./docs/overrides
  favicon: gfx/favicon_copy.svg
  logo: gfx/logo.svg
  features:
    - navigation.footer
    - content.code.annotate
    - navigation.tabs
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.footnote.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Navigation
nav:
  - Home: index.md
  # - Test: test.ipynb
  - Learn: learn/
  # - Demo: demonstration.ipynb


# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      toc_depth: 3
      permalink: ⚓︎
      title: On this page
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - _internal/javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/jupyter-code-wrapper.css

# Extra settings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aidagroup/regelum

plugins:
  - literate-nav
  - autorefs
  - macros
  - section-index
  - mkdocs-jupyter:
      include_source: True
      include_requirejs: true
      custom_mathjax_url: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
      highlight_extra_classes: "custom-css-classes"
      remove_tag_config:
        remove_cell_tags: 
          - "requirements"
