[tool.poetry]
name = "regelum"
version = "0.1.0"
description = ""
authors = ["Georgiy Malaniya <pwlsd.gm@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "regelum", from = "." },
    { include = "regelum/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.11"
casadi = "^3.6.7"
torch = "^2.4.1"
pandas = "^2.2.3"
omegaconf = "^2.3.0"
scipy = "^1.14.1"

# Dev dependencies as optional
pytest = {version = "^8.3.4", optional = true}
pre-commit = {version = "^3.6.0", optional = true}
mkdocs-material = {version = "^9.5.47", optional = true}
mkdocs-autorefs = {version = "^1.2.0", optional = true}
mkdocs-macros-plugin = {version = "^1.0.5", optional = true}
mkdocs-gen-files = {version = "^0.5.0", optional = true}
mkdocs-literate-nav = {version = "^0.6.1", optional = true}
mkdocs-section-index = {version = "^0.3.8", optional = true}
mkdocs-jupyter = {version = "^0.25.1", optional = true}

black = {version = "^24.3.0", optional = true}
matplotlib = "^3.9.2"


[tool.poetry.extras]
dev = ["pytest", "pre-commit", "mkdocs-material", "black"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
