version: '3'

services:
  mkdocs:
    image: python:3.12-slim
    working_dir: /docs
    volumes:
      - ..:/docs
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/docs
    command: >
      bash -c "
        pip install --upgrade pip &&
        pip install mkdocs mkdocs-material mkdocs-jupyter mdx-include pymdown-extensions &&
        pip install mkdocs-literate-nav mkdocs-section-index mkdocs-autorefs mkdocs-macros-plugin &&
        pip install mkdocs-gen-files mkdocstrings mkdocstrings-python &&
        cd /docs &&
        mkdocs serve -a 0.0.0.0:8000
      "

  mkdocs-build:
    image: python:3.12-slim
    working_dir: /docs
    volumes:
      - ..:/docs
    environment:
      - PYTHONPATH=/docs
    command: >
      bash -c "
        pip install --upgrade pip &&
        pip install mkdocs mkdocs-material mkdocs-jupyter mdx-include pymdown-extensions &&
        pip install mkdocs-literate-nav mkdocs-section-index mkdocs-autorefs mkdocs-macros-plugin &&
        pip install mkdocs-gen-files mkdocstrings mkdocstrings-python &&
        cd /docs &&
        mkdocs build
      " 