name: Pylint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run pylint
      run: |
        pylint $(find regelum -path "regelum/utils" -prune -o -name "*.py" -print) --output-format=text | tee ./pylint.txt || true
        PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint.txt)
        echo "Raw pylint output:"
        cat ./pylint.txt
        echo "Extracted score: $PYLINT_SCORE"
        if [ -z "$PYLINT_SCORE" ]; then
          PYLINT_SCORE="0.0"
        fi
        echo "PYLINT_SCORE=$PYLINT_SCORE" >> $GITHUB_ENV
    - name: Update README badge
      if: github.event_name == 'push'
      run: |
        COLOR=$([ $(echo "$PYLINT_SCORE >= 9" | bc -l) -eq 1 ] && echo "brightgreen" || \
               [ $(echo "$PYLINT_SCORE >= 7" | bc -l) -eq 1 ] && echo "green" || \
               [ $(echo "$PYLINT_SCORE >= 5" | bc -l) -eq 1 ] && echo "yellow" || echo "red")
        sed -i "s#https://img.shields.io/badge/pylint-[0-9.]*%2F10-[a-z]*#https://img.shields.io/badge/pylint-${PYLINT_SCORE}%2F10-${COLOR}#" README.md
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git commit -m "Update pylint badge score: ${PYLINT_SCORE}/10" || echo "No changes to commit"
        git push
