name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Run pylint
      run: |
        poetry run pylint regelum --output-format=text | tee ./pylint.txt || true
        PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint.txt)
        echo "PYLINT_SCORE=$PYLINT_SCORE" >> $GITHUB_ENV
    - name: Create Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 3dfb2d83654be9d67d432229a99cebbe
        filename: pylint.json
        label: pylint
        message: ${{ env.PYLINT_SCORE }}/10
        color: green
